ci: install test-run deps via pip instead of apt
This patch fixes the following issue:

    Installing collected packages: greenlet, gevent
      Attempting uninstall: greenlet
        Found existing installation: greenlet 0.4.15
    ERROR: Cannot uninstall 'greenlet'. It is a distutils installed
        project and thus we cannot accurately determine which files
        belong to it which would lead to only a partial uninstall.
    make: *** [.travis.mk:86: deps_tests] Error 1
    Error: Process completed with exit code 2.

This happens because the `python3-gevent` package is installed via the
`apt` package manager in some test targets. Let's install test-run deps
via `pip` everywhere.

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci