ci: ignore fail on artifact upload to S3 for osx
From time to time, the step to upload job artifacts to S3 fails due to
the following error:

    Error: Unable to retrieve job ID by provided job name

It happens in the `s3-upload-artifact` action that tries to get job ID
by the name via the `get-job-id` action. Job ID is needed to compose the
proper artifact name. `get-job-id` performs a request to GitHub for the
list of workflow jobs and finds the job by its name and then gets its
ID.

For some reason, sometimes GitHub doesn't give the complete job list and
there is no chance to find the job and get its ID. At least, it has been
noticed for the osx.yml workflow with 36 parallel jobs.

It looks like the issue resides on the GitHub side and the simplest way
to resolve this is to ignore the failure and not fail the whole workflow
due to this GitHub bug.

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci