build: LTO release build fails
LTO build failed because of warnings on the uninitialized
variables treated as errors:

/mnt/src/box/tuple_update.c: In function ‘do_op_splice’:
/mnt/src/box/tuple_update.c:764:15: error: ‘str_len’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   arg->offset = str_len;
               ^
/mnt/src/box/tuple_update.c:755:10: note: ‘str_len’ was declared here
  int32_t str_len;
          ^
/mnt/src/box/tuple_update.c: In function ‘do_op_bit’:
/mnt/src/box/tuple_update.c:725:12: error: ‘val’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   arg->val &= val;
            ^
/mnt/src/box/tuple_update.c:720:11: note: ‘val’ was declared here
  uint64_t val;
           ^
/mnt/src/box/tuple_update.c: In function ‘update_read_ops’:
/mnt/src/box/tuple_update.c:1068:4: error: ‘field_no’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    diag_set(ClientError, ER_NO_SUCH_FIELD_NO, field_no);
    ^
/mnt/src/box/tuple_update.c:1057:10: note: ‘field_no’ was declared here
  int32_t field_no;
          ^
lto1: all warnings being treated as errors

Fixed by setting variables to 0 value on initializations.

Closed #4512