error: fix ER_CANT_UPDATE_PRIMARY_KEY template
This client error assumes two arguments: space's name and index's name.
Since from the context it's clear that primary index is affected,
let's drop index name from error message. It's quite handy for space
upgrade case, since in such situation we have lack of information
concerning space.

NO_CHANGELOG=<Minor change>
NO_DOC=<No functional changes>